---
start-url: https://stackoverflow.com/
path: questions
posts-class-name: .s-post-summary
votes-class-name: .s-post-summary--stats-item-number
tags-class-name: .post-tag
single-tag-class-name: .js-tagname-
...